name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: docker build -t vnc-cloudflared:test .
    
    - name: Verify Docker image
      run: |
        docker images | grep vnc-cloudflared
        docker run --rm vnc-cloudflared:test cloudflared version
    
  test-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    
    - name: Test script syntax
      run: |
        shellcheck vnc-client.sh || true
        bash -n vnc-client.sh
    
    - name: Check file permissions
      run: |
        ls -la vnc-client.sh
        test -x vnc-client.sh || (echo "Script not executable" && exit 1)
    
  validate-compose:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate docker-compose.yml
      run: |
        docker compose config
        docker compose --dry-run up